// This file will be auto-generated by running: npm run db:generate-types
// It contains TypeScript types for all Supabase database tables

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            user_profiles: {
                Row: {
                    id: string
                    email: string
                    subscription_tier: 'free' | 'pro' | 'enterprise'
                    ai_usage_count: number
                    ai_usage_reset_date: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    subscription_tier?: 'free' | 'pro' | 'enterprise'
                    ai_usage_count?: number
                    ai_usage_reset_date?: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    subscription_tier?: 'free' | 'pro' | 'enterprise'
                    ai_usage_count?: number
                    ai_usage_reset_date?: string
                    created_at?: string
                    updated_at?: string
                }
            }
            saved_connections: {
                Row: {
                    id: string
                    user_id: string
                    name: string
                    database_type: 'mongodb' | 'mysql' | 'postgresql' | 'sqlite'
                    encrypted_config: string
                    is_active: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    name: string
                    database_type: 'mongodb' | 'mysql' | 'postgresql' | 'sqlite'
                    encrypted_config: string
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    name?: string
                    database_type?: 'mongodb' | 'mysql' | 'postgresql' | 'sqlite'
                    encrypted_config?: string
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
            query_history: {
                Row: {
                    id: string
                    user_id: string
                    connection_id: string | null
                    query_text: string
                    query_type: string | null
                    execution_time: number | null
                    row_count: number | null
                    success: boolean
                    error_message: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    connection_id?: string | null
                    query_text: string
                    query_type?: string | null
                    execution_time?: number | null
                    row_count?: number | null
                    success?: boolean
                    error_message?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    connection_id?: string | null
                    query_text?: string
                    query_type?: string | null
                    execution_time?: number | null
                    row_count?: number | null
                    success?: boolean
                    error_message?: string | null
                    created_at?: string
                }
            }
            chat_sessions: {
                Row: {
                    id: string
                    user_id: string
                    connection_id: string | null
                    title: string | null
                    session_data: Json
                    is_active: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    connection_id?: string | null
                    title?: string | null
                    session_data?: Json
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    connection_id?: string | null
                    title?: string | null
                    session_data?: Json
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
            payments: {
                Row: {
                    id: string
                    user_id: string
                    paddle_payment_id: string | null
                    paddle_subscription_id: string | null
                    amount: number
                    currency: string
                    status: 'pending' | 'succeeded' | 'failed' | 'canceled' | 'refunded'
                    payment_method: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    paddle_payment_id?: string | null
                    paddle_subscription_id?: string | null
                    amount: number
                    currency?: string
                    status: 'pending' | 'succeeded' | 'failed' | 'canceled' | 'refunded'
                    payment_method?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    paddle_payment_id?: string | null
                    paddle_subscription_id?: string | null
                    amount?: number
                    currency?: string
                    status?: 'pending' | 'succeeded' | 'failed' | 'canceled' | 'refunded'
                    payment_method?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            ai_usage_logs: {
                Row: {
                    id: string
                    user_id: string
                    usage_type: 'query_generation' | 'chat_message' | 'query_optimization'
                    tokens_used: number
                    cost_cents: number
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    usage_type: 'query_generation' | 'chat_message' | 'query_optimization'
                    tokens_used?: number
                    cost_cents?: number
                    created_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    usage_type?: 'query_generation' | 'chat_message' | 'query_optimization'
                    tokens_used?: number
                    cost_cents?: number
                    created_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
}